# Generated by Django 6.0.3 on 2026-03-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminApp", "0002_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="features",
            field=models.JSONField(default=list),
        ),
    ]
