# Generated by Django 6.0.3 on 2026-03-30 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminApp", "0003_services_features"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item_Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=100)),
                ("price", models.IntegerField(max_length=40)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AdminApp.services",
                    ),
                ),
            ],
        ),
    ]
