# Generated by Django 6.0.3 on 2026-04-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminApp", "0004_item_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item_price",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
