# Generated by Django 6.0.3 on 2026-04-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminApp", "0005_alter_item_price_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=20,
            ),
        ),
    ]
