# Generated by Django 6.0.3 on 2026-03-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='category',
            field=models.TextField(default='null'),
        ),
    ]
