# Generated by Django 6.0.3 on 2026-03-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_rename_schedule_service_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_booking',
            name='category',
        ),
        migrations.AddField(
            model_name='service_booking',
            name='Delivery_mode',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Express', 'Express')], default='null', max_length=10),
        ),
    ]
