# Generated by Django 6.0.3 on 2026-03-17 07:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_remove_service_booking_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_booking',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
