# Generated by Django 6.0.3 on 2026-03-17 07:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_alter_service_booking_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_booking',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
